routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\NoteController;

Auth::routes();

Route::get('/about', function () {
	return view('about');
});

Route::get('/', 'HomeController@index')->name('homepage');

Route::group(['middleware' => 'auth'], function () {

	Route::resource('users', 'UserController');
	Route::resource('roles', 'RoleController');
	Route::resource('permissions', 'PermissionController');

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes

	Route::middleware(['role:admin,list-clients,edit-clients'])->group(function(){

		// Route::get('/clients', 'ClientsController@index')->name('clients.index');
		// Route::post('/clients', 'ClientsController@store')->name('clients.store');
		// Route::get('/clients/create', 'ClientsController@create')->name('client.create');
		// Route::get('/clients/{client}/edit', 'ClientsController@edit')->name('client.edit');
		// Route::put('/clients/{client}', 'ClientsController@update')->name('client.update');

		Route::resource('/clients', 'ClientsController');

	});



	Route::middleware(['role:client,list-rates,list-customers,list-meters'])->group(function () {


		Route::resource('/meter-type', 'MeterTypeController');
		Route::resource('/route', 'RouteController');
		Route::resource('/zone', 'ZoneController');
		Route::resource('/tax-code', 'TaxCodeController');
		Route::resource('/billing-period', 'BillingPeriodController');
		Route::resource('/custom-charge', 'CustomChargeController');


		Route::resource('rates', 'RateController');
		Route::get('/rates/{rate}/edit', 'RateController@edit')->name('rates.edit');

		// Route::get('/water-rates', 'WaterRateController@index')->name('water-rates.index');
		// Route::post('/water-rates', 'WaterRateController@store')->name('water-rates.store');
		// Route::get('/water-rates/create', 'WaterRateController@create')->name('water-rates.create');
		// Route::get('/water-rates/{id}', 'WaterRateController@show')->name('water-rates.show');
		// Route::get('/water-rates/{rate}/edit', 'WaterRateController@edit')->name('water-rates.edit');
		// Route::put('/water-rates/{rate}', 'WaterRateController@update')->name('water-rates.update');

		Route::resource('/water-rates', 'WaterRateController');


		// Route::get('/customers', 'CustomerController@index')->name('customers.index');
		// Route::post('/customers', 'CustomerController@store')->name('customers.store');
		// Route::get('/customers/create', 'CustomerController@create')->name('customers.create');
		// Route::get('/customers/{customer}', 'CustomerController@show')->name('customers.show');
		// Route::get('/customers/{customer}/edit', 'CustomerController@edit')->name('customers.edit');
		// Route::put('/customers/{customer}', 'CustomerController@update')->name('customers.update');
		// Route::delete('/customers/{customer}', 'CustomerController@destroy')->name('customers.destroy');

		Route::resource('/customers', 'CustomerController');


		Route::get('/notes/', 'NoteController@index')->name('notes');
		Route::put('/notes/{note}', 'NoteController@update')->name('notes.update');
		Route::delete('notes/{note}', 'NoteController@destroy')->name('notes.destroy');
		Route::get('/notes/updateTable/{module}/{id}', 'NoteController@updateTableContainer')->name('notes.update-table');

		Route::get('/customers/{customer}/notes', 'NoteController@CustomerIndex')->name('customers-notes.index');
		Route::post('/customers/{customer}/note', 'CustomerController@addNote')->name('customers-note.add');

		Route::post('/meters/{meter}/note', 'MeterController@addNote')->name('meters-note.add');



		Route::get('/meters', 'MeterController@index')->name('meters.index');
		Route::get('/meters/water/free', 'MeterController@getUnasigned')->name('meters.unasigned');
		Route::post('/meters/assign', 'MeterController@addCustomer')->name('meters.addCustomer');

		Route::post('/customers/{customer}/meters', 'MeterController@store')->name('meters.create');
		Route::post('/meters/{meter}/removeCustomer', 'MeterController@removeCustomer')->name('meters.remove-customer');
		Route::post('/meters/{meter}/setOutofOrder', 'MeterController@setOutofOrder')->name('meters.outoforder');
		Route::get('/meters/{meter}/edit', 'MeterController@edit')->name('meters.edit');
		Route::put('/meters/{meter}', 'MeterController@update')->name('meters.update');
		Route::delete('/meters/{meter}', 'CustomerController@destroy')->name('meters.destroy');


		Route::get('/readings', 'ReadingController@index')->name('readings.index');

	});






});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Lecturize\Addresses\Traits\HasAddresses;

class Client extends Model
{
	//
	use HasAddresses;
	use SoftDeletes;


	protected $fillable = [
		'company_name', 'first_name', 'last_name', 'service_charge_rate', 'late_fee_amount', 'minimum_balance'
	];

	//	$client = Client::with('user', 'addresses.country')->get();
	//	protected $guarded = ['addresses'];
	//	protected $with = ['user', 'addresses', 'addresses.country'];


	public function user() {

		return $this->morphOne(User::class, 'userable');
	}

	public function rates()
	{
		return $this->hasMany(Rate::class);
	}

	public function customers() {

		return $this->hasMany(Customer::class);
	}

	public function roles() {
		return $this->user->roles();
	}

	public function getFullNameAttribute() {

		return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
	}


}

app/Reading.php
<?php

namespace App;

class Reading extends Model
{

    protected $table = 'readings';
    public $timestamps = true;

    public function meter()
    {
        return $this->belongsTo(Meter::class);
    }


	public function scopeLastNth($query, $count)
	{

		$readings = $query->take($count)->latest();

		return $readings;

    }

}

app/Http/Controllers/ReadingController.php
<?php

namespace App\Http\Controllers;

use App\Meter;
use App\Reading;

class ReadingController extends Controller
{

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{

		$meters = Meter::with('readings', 'customer')->get();

		return view('readings.index', compact('meters'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{

	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{

	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function show($id)
	{

	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function edit($id)
	{

	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function update($id)
	{

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 * @return Response
	 */
	public function destroy($id)
	{

	}

}

?>

resources/views/readings/index.blade.php
@extends('adminlte::page')

@section('htmlheader_title')
    Readings
@endsection

@section('contentheader_title')
    Readings
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-12">

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Readings</h3>
                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">


                        <table class="table table-hover table-responsive table-striped">

                            <thead>
                            <tr>
                                <th>Meter Serial #</th>
                                <th>Name</th>
                                <th>Previous</th>
                                <th>Last Reading</th>
                                <th>New Reading</th>
                                <th>Date</th>
                                <th>Units</th>
                                <th>Actions</th>
                            </tr>
                            </thead>

                            <tbody>

                            @foreach($meters as $meter)

                                <tr>
                                    <td>{{ $meter->serial }}</td>
                                    <td>{{ $meter->customer->full_name }}</td>
                                    <td>
                                        @if(!$meter->readings->isEmpty())
                                            {{ $meter->readings->get(1)->reading }}
                                        @endif

                                        @if(!$meter->readingsLast(2)->get()->isEmpty())
                                            {{ $meter->readingsLast(2)->get()->reverse()->first()->reading }}
                                        @endif()
                                    </td>
                                    <td>
                                        @if(!$meter->readings->isEmpty())
                                            {{ $meter->readings->first()->reading }}
                                        @endif

                                        @if(!$meter->readingsLast(2)->get()->isEmpty())
                                            {{ $meter->readingsLast(2)->get()->reverse()->last()->reading }}
                                        @endif()
                                    </td>
                                    <td>
                                        <input type="text"/>
                                    </td>
                                    <td><input type="date"/></td>
                                    <td></td>
                                    <td>
                                        <button class="btn btn-info btn-sm pull-left margin-r-5" data-meter="{{$meter->id}}">Calculate Estimate</button>
                                    </td>
                                </tr>

                            @endforeach

                            </tbody>


                        </table>


                    </div>
                    <!-- /.box-body -->
                </div>

            </div>
        </div>
    </div>
@endsection